<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: sans-serif; font-size: 12px; color: #1a1a1a; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #333; padding-bottom: 10px; }
        .header h1 { margin: 0; font-size: 20px; }
        .header p { margin: 2px 0; color: #555; }
        .section { margin-bottom: 20px; }
        .section-title { font-size: 14px; font-weight: bold; background: #f0f0f0; padding: 6px 10px; margin-bottom: 8px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
        th, td { border: 1px solid #ddd; padding: 6px 8px; text-align: left; }
        th { background: #f7f7f7; }
        .stats { display: table; width: 100%; margin-bottom: 15px; }
        .stat { display: table-cell; width: 25%; text-align: center; padding: 10px; border: 1px solid #ddd; }
        .stat .value { font-size: 18px; font-weight: bold; }
        .stat .label { font-size: 10px; color: #666; }
        .danger { color: #c0392b; }
        .warning { color: #d68910; }
        .footer { margin-top: 30px; text-align: center; font-size: 10px; color: #999; }
    </style>
</head>
<body>

    <div class="header">
        <h1>{{ config('app.name', 'Pharmacera') }}</h1>
        <p>{{ $label }} Report</p>
        <p>Generated by {{ $generated_by }} on {{ $generated_at->format('M j, Y H:i') }}</p>
    </div>

    <div class="stats">
        <div class="stat">
            <div class="value">{{ number_format($totalRevenue, 2) }} {{ $currency }}</div>
            <div class="label">Total Revenue</div>
        </div>
        <div class="stat">
            <div class="value">{{ $totalSales }}</div>
            <div class="label">Transactions</div>
        </div>
        <div class="stat">
            <div class="value">{{ number_format($averageSale, 2) }} {{ $currency }}</div>
            <div class="label">Average Sale</div>
        </div>
        <div class="stat">
            <div class="value">{{ number_format($stockValue, 2) }} {{ $currency }}</div>
            <div class="label">Stock Value</div>
        </div>
    </div>

    <div class="section">
        <div class="section-title">Sales by Payment Method</div>
        <table>
            <tr><th>Method</th><th>Transactions</th><th>Total</th></tr>
            @forelse($byPaymentMethod as $method => $data)
                <tr>
                    <td>{{ ucfirst($method) }}</td>
                    <td>{{ $data['count'] }}</td>
                    <td>{{ number_format($data['total'], 2) }} {{ $currency }}</td>
                </tr>
            @empty
                <tr><td colspan="3">No sales in this period</td></tr>
            @endforelse
        </table>
    </div>

    <div class="section">
        <div class="section-title">Sales by Staff</div>
        <table>
            <tr><th>Staff</th><th>Transactions</th><th>Total</th></tr>
            @forelse($byStaff as $name => $data)
                <tr>
                    <td>{{ $name }}</td>
                    <td>{{ $data['count'] }}</td>
                    <td>{{ number_format($data['total'], 2) }} {{ $currency }}</td>
                </tr>
            @empty
                <tr><td colspan="3">No sales in this period</td></tr>
            @endforelse
        </table>
    </div>

    <div class="section">
        <div class="section-title">Top Selling Medicines</div>
        <table>
            <tr><th>#</th><th>Medicine</th><th>Quantity Sold</th><th>Revenue</th></tr>
            @forelse($topMedicines as $i => $item)
                <tr>
                    <td>{{ $i + 1 }}</td>
                    <td>{{ $item['medicine']?->name ?? 'Deleted medicine' }}</td>
                    <td>{{ $item['quantity'] }}</td>
                    <td>{{ number_format($item['revenue'], 2) }} {{ $currency }}</td>
                </tr>
            @empty
                <tr><td colspan="4">No sales in this period</td></tr>
            @endforelse
        </table>
    </div>

    <div class="section">
        <div class="section-title">Low Stock Medicines ({{ $lowStock->count() }})</div>
        <table>
            <tr><th>Medicine</th><th>Current Stock</th><th>Alert Threshold</th></tr>
            @forelse($lowStock as $medicine)
                <tr>
                    <td>{{ $medicine->name }}</td>
                    <td class="danger">{{ $medicine->stock_sum }}</td>
                    <td>{{ $medicine->alert_threshold }}</td>
                </tr>
            @empty
                <tr><td colspan="3">No low stock medicines</td></tr>
            @endforelse
        </table>
    </div>

    <div class="section">
        <div class="section-title">Expiring Within 30 Days ({{ $expiringSoon->count() }})</div>
        <table>
            <tr><th>Medicine</th><th>Batch Qty</th><th>Expiry Date</th></tr>
            @forelse($expiringSoon as $batch)
                <tr>
                    <td>{{ $batch->medicine->name }}</td>
                    <td>{{ $batch->remaining_quantity }}</td>
                    <td class="warning">{{ $batch->expiry_date->format('M j, Y') }}</td>
                </tr>
            @empty
                <tr><td colspan="3">Nothing expiring soon</td></tr>
            @endforelse
        </table>
    </div>

    <div class="section">
        <div class="section-title">Expired Stock — Loss Report ({{ $expired->count() }} batches, {{ number_format($expiredValue, 2) }} {{ $currency }})</div>
        <table>
            <tr><th>Medicine</th><th>Batch Qty</th><th>Expired On</th><th>Value Lost</th></tr>
            @forelse($expired as $batch)
                <tr>
                    <td>{{ $batch->medicine->name }}</td>
                    <td>{{ $batch->remaining_quantity }}</td>
                    <td class="danger">{{ $batch->expiry_date->format('M j, Y') }}</td>
                    <td class="danger">{{ number_format($batch->remaining_quantity * $batch->purchase_price, 2) }} {{ $currency }}</td>
                </tr>
            @empty
                <tr><td colspan="4">No expired stock</td></tr>
            @endforelse
        </table>
    </div>

    <div class="footer">
        Pharmacera — Report period: {{ $start->format('M j, Y') }} to {{ $end->format('M j, Y') }}
    </div>

</body>
</html>